# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest

stages: 
  - validate
  - deploy_minio
  - deploy_master
  

validate:
  stage: validate
  script:
    - sh infra-deploy.sh validate
  only:
    refs:
      - master
  tags:
    - docker
    - terraform

deploy_minio:
  stage: deploy_minio
  script:
    - sh infra-deploy.sh deploy minio
  only:
    refs:
      - master
  tags:
    - docker
    - terraform

deploy_master:
  stage: deploy_master
  script:
    - sh infra-deploy.sh deploy master
  only:
    refs:
      - master
  tags:
    - docker
    - terraform

variables:
  GIT_STRATEGY: clone