# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest

# stages: 
#  - kube_deploy
#   - get_kubeconfig
#   - deploy_master
  

kube_deploy:
  script:
    - kubectl --insecure-skip-tls-verify apply -f KubernetesDeployments/videoapp-deploy.yaml
    - kubectl --insecure-skip-tls-verify apply -f KubernetesDeployments/videoapp-svc.yaml
    - kubectl --insecure-skip-tls-verify get svc 
    - kubectl --insecure-skip-tls-verify get pods
  only:
    refs:
    - Kube-deploy
  tags:
    - docker
    - terraform

variables:
  GIT_STRATEGY: clone
