---
- hosts: kubernetes-worker-nodes
  become: yes
  vars_files:
  - ../env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src=/home/centos/{{ token_file }} dest=/home/centos/join_token

  - name: Rebooting the machine to disable SELINUX
    reboot:
      reboot_timeout: 3600

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat /home/centos/join_token | tail -2 > out.sh
     sh out.sh
