---
- hosts: all
  become: yes
  vars_files:
  - ../env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: /usr/sbin/swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  
